import { saveTariff } from "@/app/dashboard/actions";
import { DashboardBadge } from "@/components/dashboard/DashboardBadge";
import { formatCurrency } from "@/components/dashboard/format";
import { getTariffs, getZones } from "@/server/dashboard/queries";

export const dynamic = "force-dynamic";

export default async function TariffsPage() {
  const [tariffs, zones] = await Promise.all([getTariffs(), getZones()]);
  return <div className="grid gap-6 lg:grid-cols-[0.85fr_1.25fr]"><section className="rounded-card border border-border bg-surface p-6"><h2 className="text-2xl font-extrabold text-brand-strong">Nueva tarifa activa</h2><form action={saveTariff} className="mt-5 space-y-4"><label className="block text-sm font-bold text-ink">Zona<select name="zoneId" required className="mt-2 min-h-12 w-full rounded-input border border-border px-4">{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label className="block text-sm font-bold text-ink">Tipo<select name="vehicleKind" className="mt-2 min-h-12 w-full rounded-input border border-border px-4"><option value="auto">Auto</option><option value="moto">Moto</option></select></label><Field name="label" label="Etiqueta" /><Field name="hourlyRateCents" label="Valor por hora en centavos" type="number" /><Field name="digitalDiscountPercent" label="Descuento digital (%)" type="number" /><button className="rounded-pill bg-brand px-5 py-3 text-sm font-bold text-white" type="submit">Activar tarifa</button><p className="text-xs text-ink-soft">No existe borrado destructivo de tarifas. Al activar una nueva, la anterior queda histórica y los pagos conservan sus montos.</p></form></section><section><h2 className="text-3xl font-extrabold text-brand-strong">Tarifas</h2><div className="mt-5 space-y-3">{tariffs.map((tariff) => <article key={tariff.id} className="rounded-card border border-border bg-surface p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-extrabold text-ink">{tariff.zoneName} · {tariff.label}</h3><p className="text-sm text-ink-soft">{tariff.vehicleKind} · {formatCurrency(tariff.hourlyRateCents)} por hora · {tariff.digitalDiscountPercent}% digital</p></div><DashboardBadge tone={tariff.active ? "confirmed" : "neutral"}>{tariff.active ? "Activa" : "Histórica"}</DashboardBadge></div></article>)}</div></section></div>;
}

function Field({ name, label, type = "text" }: { name: string; label: string; type?: string }) { return <label className="block text-sm font-bold text-ink">{label}<input name={name} type={type} required className="mt-2 min-h-12 w-full rounded-input border border-border px-4 outline-none focus-visible:ring-4 focus-visible:ring-brand/20" /></label>; }
